server:
  port: 8002
management:
  endpoint:
    health:
      show-details: always
info:
  appneme: user
  author: wsl
#  指定到nacos
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  application:
    name: social-center
    # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/cultivation?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
