#指定端口号
server:
  port: 8003
#是否显示详细信息
management:
  endpoint:
    health:
      show-details: always
info:
  appneme: user
  author: wsl
#  指定到nacos server
spring:
  cloud:
    nacos:
      discovery:
#        nacos的服务地址
        server-addr: localhost:8848
#        指定命名空间
#        namespace:
#          指定集群
#        cluster-name:
  #        服务名称
  application:
    name:  facility-center
  #   连接数据源
  datasource:
    url: jdbc:mysql://localhost:3306/cultivation?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
